FROM ubuntu:20.04
ARG BUILD_VER=3.2
ARG TARGET_DIR=/opt/nubomanagement
LABEL build_ver="${BUILD_VER}"


# install linux packages
RUN apt-get -y update
RUN apt install -y \
    curl \
    gnupg \
    ca-certificates \
    lsb-release \
    supervisor \
    vim \
    iputils-ping \
    telnet \
    dnsutils \
    net-tools \
    openssh-client \
    rsync \
    lib32stdc++6 \
    lib32z1 \
    zip \
    unzip \
    openjdk-8-jdk \
    sudo

# install nodejs
RUN mkdir -p /etc/apt/keyrings && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
RUN apt-get update && apt install -y nodejs


#install docker-ce-cli
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
RUN echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
RUN apt update -y ; apt install -y docker-ce-cli

# # configure files
ADD docker_build/etc /etc
ADD docker_build/bin /usr/local/bin
RUN mkdir -p /var/log/supervisor/

# mark this as docker installation
RUN mkdir -p /etc/.nubo/ && \
    touch  /etc/.nubo/.docker

# copy files to target dir
RUN mkdir -p ${TARGET_DIR}
COPY package.json ${TARGET_DIR}/.
COPY webpack.config.js ${TARGET_DIR}/.
ADD src ${TARGET_DIR}/src
ADD nubo-management-enterprise ${TARGET_DIR}/nubo-management-enterprise
ADD nubo-management-mobile ${TARGET_DIR}/nubo-management-mobile
ADD scripts ${TARGET_DIR}/scripts
ADD utils ${TARGET_DIR}/utils
WORKDIR ${TARGET_DIR}

# RUN npm --version && node --version

# add build essential
RUN apt install -y build-essential git

# prepare the mobile/enterprise packages link
RUN ./scripts/attachEnterpriseMobileModule.sh

# prepare the static-src folder
RUN ./scripts/prepareStaticSrc.sh

# remove build-essntial
RUN apt-get --purge autoremove -y build-essential git

# build the dist folder
RUN npm run build

# delete the sources
RUN if [[ -z "$dev" ]] ; then rm -rf src webpack.config.js nubo-management-enterprise/src nubo-management-mobile/src ; else echo "Development build - not deleting sources" ; fi
#RUN rm -rf src webpack.config.js nubo-management-enterprise/src nubo-management-mobile/src


# Docker config
VOLUME ["/opt/nubomanagement/conf","/opt/nubomanagement/locales","/opt/nubomanagement/docker_apps","/srv/nfs/homes"]
EXPOSE 8443 8080
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["supervisord", "--nodaemon", "--configuration", "/etc/supervisor/supervisord.conf"]
