FROM node:16-alpine3.15
ARG BUILD_VER=3.2
ARG TARGET_DIR=/opt/nubomanagement
LABEL build_ver="${BUILD_VER}"

# add required packages
RUN apk add --update supervisor curl rsyslog sudo docker

# temporary add build dependencies
RUN apk add --no-cache --virtual .build-deps-full \
        binutils-gold \
        g++ \
        gcc \
        gnupg \
        libgcc \
        linux-headers \
        make \
        python3


# # configure files
ADD docker_build/etc /etc
ADD docker_build/bin /usr/local/bin
RUN mkdir -p /var/log/supervisor/
#RUN sed -i /imklog/s/module/#module/ /etc/rsyslog.conf

# mark this as docker installation
RUN mkdir -p /etc/.nubo/ && \
    touch  /etc/.nubo/.docker

# copy files to target dir
RUN mkdir -p ${TARGET_DIR}
COPY package.json ${TARGET_DIR}/.
COPY webpack.config.js ${TARGET_DIR}/.
ADD src ${TARGET_DIR}/src
ADD nubo-management-desktop ${TARGET_DIR}/nubo-management-desktop
ADD scripts ${TARGET_DIR}/scripts
ADD utils ${TARGET_DIR}/utils
WORKDIR ${TARGET_DIR}

# prepare the desktop module
RUN ./scripts/attachDesktopModule.sh

# build the dist folder
RUN npm run build
RUN rm -rf src webpack.config.js nubo-management-desktop/src

# remove build dependencies
RUN apk del .build-deps-full


# Docker config
VOLUME ["/opt/nubomanagement/conf","/opt/nubomanagement/locales","/opt/nubomanagement/docker_apps","/srv/nfs/homes"]
EXPOSE 8443 8080
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["supervisord", "--nodaemon", "--configuration", "/etc/supervisor/supervisord.conf"]
