#!/bin/sh

if [ ! -f /opt/Android-Nougat/cache.img ]; then
  dd if=/dev/zero of=/opt/Android-Nougat/cache.img bs=1M count=2048 && mkfs.ext4 -F /opt/Android-KitKat/cache.img
  mkfs.ext4 -F /opt/Android-Nougat/cache.img
fi
if [ ! -f /opt/Android-Nougat/userdata.img ]; then
  dd if=/dev/zero of=/opt/Android-Nougat/userdata.img bs=1M count=2048 && mkfs.ext4 -F /opt/Android-KitKat/userdata.img
  mkfs.ext4 -F /opt/Android-Nougat/userdata.img
  tries=5;
  while true; do
    RAND_SUFFIX=`dd if=/dev/urandom count=4 bs=1 2>/dev/null | hexdump -e '/16 ""' -e '/1 "%x"' -e '/16 ""'`
    MY_DIR=/opt/Android-Nougat/mnt-${RAND_SUFFIX}
    if mkdir ${MY_DIR} 2>/dev/null ; then
      mount -o loop /opt/Android-Nougat/userdata.img ${MY_DIR}
      tar -xf /opt/Android-Nougat/userdata.tar.gz -C ${MY_DIR}
      umount ${MY_DIR}
      rmdir ${MY_DIR}
      break
    else
      echo "dir ${MY_DIR} already exist"
      tries=$((tries-1))
      if [ "$tries" -le 0 ]; then
        echo "no tries left"
        exit 1
      fi
    fi
  done
else
  echo "userdata.img already exist"
fi

tries=5;
while true; do
  RAND_SUFFIX=`dd if=/dev/urandom count=4 bs=1 2>/dev/null | hexdump -e '/16 ""' -e '/1 "%x"' -e '/16 ""'`
  MY_DIR=/opt/Android-Nougat/mnt-${RAND_SUFFIX}
  if mkdir ${MY_DIR} 2>/dev/null ; then
    mount -o loop /opt/Android-Nougat/userdata.img ${MY_DIR}
    if [ ! -f ${MY_DIR}/local/chrome-command-line ]; then
      mkdir ${MY_DIR}/local
      echo "chrome --single-process --disable-es3-gl-context --disable-es3-apis --disable-gl-error-limit" > ${MY_DIR}/local/chrome-command-line
      chmod 644 ${MY_DIR}/local/chrome-command-line
    fi
    umount ${MY_DIR}
    rmdir ${MY_DIR}
    break
  else
    echo "dir ${MY_DIR} already exist"
    tries=$((tries-1))
    if [ "$tries" -le 0 ]; then
      echo "no tries left"
      exit 1
    fi
  fi
done
